// <auto-generated />
using System;
using Emart.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Emart.Infrastructure.Data.Migrations
{
    [DbContext(typeof(EmartDbContext))]
    partial class EmartDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Emart.Domain.Entities.Cart", b =>
                {
                    b.Property<long>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("cart_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("CartId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("CartId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("cart");
                });

            modelBuilder.Entity("Emart.Domain.Entities.CartItem", b =>
                {
                    b.Property<long>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("cart_item_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("CartItemId"));

                    b.Property<long>("CartId")
                        .HasColumnType("bigint")
                        .HasColumnName("cart_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("prod_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("cart_item");
                });

            modelBuilder.Entity("Emart.Domain.Entities.Category", b =>
                {
                    b.Property<int>("CatmasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("catmaster_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CatmasterId"));

                    b.Property<string>("CatId")
                        .HasColumnType("longtext")
                        .HasColumnName("cat_id");

                    b.Property<string>("CatImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("cat_image_path");

                    b.Property<string>("CatName")
                        .HasColumnType("longtext")
                        .HasColumnName("cat_name");

                    b.Property<bool?>("Flag")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("flag");

                    b.Property<string>("SubcatId")
                        .HasColumnType("longtext")
                        .HasColumnName("subcat_id");

                    b.HasKey("CatmasterId");

                    b.ToTable("category_master");
                });

            modelBuilder.Entity("Emart.Domain.Entities.Config", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("config_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ConfigId"));

                    b.Property<string>("ConfigName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("config_name");

                    b.HasKey("ConfigId");

                    b.HasIndex("ConfigName")
                        .IsUnique();

                    b.ToTable("config_master");
                });

            modelBuilder.Entity("Emart.Domain.Entities.EmcardAccount", b =>
                {
                    b.Property<long>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("AccountId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int")
                        .HasColumnName("total_points");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("AccountId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("emcard_account");
                });

            modelBuilder.Entity("Emart.Domain.Entities.EmcardReservation", b =>
                {
                    b.Property<long>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("reservation_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ReservationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("PointsReserved")
                        .HasColumnType("int")
                        .HasColumnName("points_reserved");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("prod_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("ReservationId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("uq_emcard_user_product");

                    b.ToTable("emcard_reservation");
                });

            modelBuilder.Entity("Emart.Domain.Entities.EmcardTransaction", b =>
                {
                    b.Property<long>("TxnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("txn_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("TxnId"));

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("int")
                        .HasColumnName("balance_after");

                    b.Property<int>("BalanceBefore")
                        .HasColumnType("int")
                        .HasColumnName("balance_before");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long?>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasColumnName("points");

                    b.Property<string>("TxnType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("txn_type");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("TxnId");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_emcard_txn_order");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_emcard_txn_user");

                    b.ToTable("emcard_transaction");
                });

            modelBuilder.Entity("Emart.Domain.Entities.OrderItem", b =>
                {
                    b.Property<long>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("order_item_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("OrderItemId"));

                    b.Property<string>("BrandSnapshot")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("brand_snapshot");

                    b.Property<bool>("EmcardApplied")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("emcard_applied");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("line_total");

                    b.Property<decimal>("MrpPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("mrp_price");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<int>("PointsRedeemed")
                        .HasColumnType("int")
                        .HasColumnName("points_redeemed");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("prod_id");

                    b.Property<string>("ProductNameSnapshot")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("product_name_snapshot");

                    b.Property<string>("PurchaseMode")
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("purchase_mode");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("order_item");
                });

            modelBuilder.Entity("Emart.Domain.Entities.Orders", b =>
                {
                    b.Property<long>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("OrderId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("customer_email");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("customer_name");

                    b.Property<string>("DeliveryOption")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("delivery_option");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("order_date");

                    b.Property<decimal>("PayableTotal")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("payable_total");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("payment_status");

                    b.Property<int>("PointsBalanceAfter")
                        .HasColumnType("int")
                        .HasColumnName("points_balance_after");

                    b.Property<int>("PointsBalanceBefore")
                        .HasColumnType("int")
                        .HasColumnName("points_balance_before");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("int")
                        .HasColumnName("points_earned");

                    b.Property<int>("PointsRedeemed")
                        .HasColumnType("int")
                        .HasColumnName("points_redeemed");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("longtext")
                        .HasColumnName("shipping_address");

                    b.Property<string>("StoreLocation")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("store_location");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("TotalSavings")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total_savings");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("OrderId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("Emart.Domain.Entities.PasswordResetOtp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expiry_time");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("otp_hash");

                    b.Property<bool>("Used")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("used");

                    b.HasKey("Id");

                    b.ToTable("password_reset_otp");
                });

            modelBuilder.Entity("Emart.Domain.Entities.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("prod_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ProductId"));

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("brand");

                    b.Property<decimal>("CardholderPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("cardholder_price");

                    b.Property<decimal?>("CashRequired")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("cash_required");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("catmaster_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayType")
                        .HasColumnType("longtext")
                        .HasColumnName("display_type");

                    b.Property<string>("LongDescription")
                        .HasColumnType("longtext")
                        .HasColumnName("prod_long_desc");

                    b.Property<decimal>("MrpPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("mrp_price");

                    b.Property<string>("OfferType")
                        .HasColumnType("longtext")
                        .HasColumnName("offer_type");

                    b.Property<bool>("OnSale")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("on_sale");

                    b.Property<int?>("PointsRequired")
                        .HasColumnType("int")
                        .HasColumnName("points_required");

                    b.Property<int>("PointsToBeRedeemed")
                        .HasColumnType("int")
                        .HasColumnName("points_to_be_redeemed");

                    b.Property<string>("ProductImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("prod_image_path");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("prod_name");

                    b.Property<DateTime?>("SaleEndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("sale_end_date");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("sale_price");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("prod_short_desc");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("status");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.Property<int?>("SubCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("subcat_master_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductName")
                        .IsUnique();

                    b.HasIndex("SubCategoryId");

                    b.ToTable("product_master");
                });

            modelBuilder.Entity("Emart.Domain.Entities.ProductImage", b =>
                {
                    b.Property<long>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("image_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ImageId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("image_url");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("prod_id");

                    b.HasKey("ImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("product_image_master");
                });

            modelBuilder.Entity("Emart.Domain.Entities.ProductSpecification", b =>
                {
                    b.Property<long>("ProdDtlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("prod_dtl_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ProdDtlId"));

                    b.Property<int>("ConfigId")
                        .HasColumnType("int")
                        .HasColumnName("config_id");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("config_value");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("prod_id");

                    b.HasKey("ProdDtlId");

                    b.HasIndex("ConfigId");

                    b.HasIndex("ProductId");

                    b.ToTable("prod_dtl_master");
                });

            modelBuilder.Entity("Emart.Domain.Entities.SubCategory", b =>
                {
                    b.Property<int>("SubcatMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("subcat_master_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SubcatMasterId"));

                    b.Property<int?>("CatmasterId")
                        .HasColumnType("int")
                        .HasColumnName("catmaster_id");

                    b.Property<bool?>("Flag")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("flag");

                    b.Property<string>("SubcatId")
                        .HasColumnType("longtext")
                        .HasColumnName("subcat_id");

                    b.Property<string>("SubcatImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("subcat_image_path");

                    b.Property<string>("SubcatName")
                        .HasColumnType("longtext")
                        .HasColumnName("subcat_name");

                    b.HasKey("SubcatMasterId");

                    b.HasIndex("CatmasterId");

                    b.ToTable("subcategory_master");
                });

            modelBuilder.Entity("Emart.Domain.Entities.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("UserId"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("auth_provider");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<int>("EmcardPoints")
                        .HasColumnType("int")
                        .HasColumnName("emcard_points");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext")
                        .HasColumnName("gender");

                    b.Property<bool>("IsEmcardMember")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_emcard_member");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("Emart.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("Emart.Domain.Entities.Cart", "Cart")
                        .WithMany()
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Emart.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Emart.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Emart.Domain.Entities.Orders", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Emart.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Emart.Domain.Entities.Product", b =>
                {
                    b.HasOne("Emart.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emart.Domain.Entities.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("Emart.Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("Emart.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Emart.Domain.Entities.ProductSpecification", b =>
                {
                    b.HasOne("Emart.Domain.Entities.Config", "Config")
                        .WithMany()
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emart.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Config");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Emart.Domain.Entities.SubCategory", b =>
                {
                    b.HasOne("Emart.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CatmasterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Emart.Domain.Entities.Orders", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
